language: julia
julia:
    - 1.0
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os:
        - linux
        - osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
